# Generated by Django 4.2 on 2023-04-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="album_name",
            field=models.CharField(default="default string", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="band_name",
            field=models.CharField(default="default string", max_length=50),
        ),
    ]
