# Generated by Django 4.2 on 2023-04-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_album_name_alter_post_band_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profile_pics"
            ),
        ),
    ]
